"use client";
import { useEffect, useMemo, useState } from "react";

export default function PlanningPanel({ weather, place }: { weather: any; place: any }) {
  const [air, setAir] = useState<any>(null); const [threshold, setThreshold] = useState(70);
  useEffect(() => { setThreshold(Number(localStorage.getItem("weatherly-rain-threshold") || 70)); }, []);
  useEffect(() => { const refreshAir = () => fetch(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${place.latitude}&longitude=${place.longitude}&current=pm2_5,pm10,ozone,alder_pollen,birch_pollen,grass_pollen,ragweed_pollen`, { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error("Air quality request failed"); return response.json(); }).then(d => setAir(d.current)).catch(() => setAir(null)); refreshAir(); const id = window.setInterval(refreshAir, 300000); return () => window.clearInterval(id); }, [place]);
  const daily = weather?.daily || {}; const minute = weather?.minutely_15 || {}; const hourly = weather?.hourly || {}; const weatherDate = String(weather?.current?.time || "").slice(0, 10); const dayIndex = Math.max(0, (daily.time || []).findIndex((time: string) => time === weatherDate)); const hourIndex = Math.max(0, (hourly.time || []).findIndex((time: string) => time >= String(weather?.current?.time || ""))); const rain = Number(daily.precipitation_probability_max?.[dayIndex] || 0); const now = Number(weather?.current?.temperature_2m || 0); const yesterday = Number(daily.temperature_2m_max?.[Math.max(0, dayIndex - 1)] || 0); const high = Number(daily.temperature_2m_max?.[dayIndex] || 0); const low = Number(daily.temperature_2m_min?.[dayIndex] || 0); const nextDayRain = (hourly.precipitation || []).slice(hourIndex, hourIndex + 24).reduce((sum: number, amount: number) => sum + Number(amount || 0), 0);
  const outfit = now < 5 ? "Bring a warm coat." : rain >= threshold ? "Bring a waterproof layer or umbrella." : now > 24 ? "Light layers and water are a good idea." : "Comfortable layers should work well.";
  const nextRain = useMemo(() => (minute.precipitation_probability || []).findIndex((n: number) => n >= threshold), [minute, threshold]);
  const pollen = air ? Math.max(...[air.alder_pollen, air.birch_pollen, air.grass_pollen, air.ragweed_pollen].filter(Number.isFinite), 0) : null;
  const rainRisk = nextDayRain >= 30 ? "Elevated" : nextDayRain >= 15 ? "Watch conditions" : "Low";
  return <section className="planning-panel" aria-label="Daily planning tools"><article><p className="eyebrow">YOUR DAY</p><h2>{rain >= threshold ? "Plan for rain" : "A calm weather day"}</h2><p>{outfit}</p><small>{nextRain >= 0 ? `Rain chance reaches ${threshold}% around ${new Date(minute.time[nextRain]).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}.` : "No high-probability rain window in the next few hours."}</small></article><article><p className="eyebrow">15-MINUTE OUTLOOK</p><div className="minute-strip">{(minute.time || []).slice(0, 8).map((time: string, i: number) => <span key={time}><b>{Math.round(minute.precipitation_probability?.[i] || 0)}%</b><small>{new Date(time).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</small></span>)}</div></article><article><p className="eyebrow">SUN & HISTORY</p><strong>↑ {high.toFixed(0)}° · ↓ {low.toFixed(0)}°</strong><p>Yesterday’s high: {yesterday.toFixed(0)}°</p><small>Sunrise {daily.sunrise?.[dayIndex] ? new Date(daily.sunrise[dayIndex]).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }) : "—"} · Sunset {daily.sunset?.[dayIndex] ? new Date(daily.sunset[dayIndex]).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }) : "—"}</small></article><article><p className="eyebrow">AIR & POLLEN</p><strong>PM2.5 {air?.pm2_5?.toFixed?.(0) ?? "—"} · O₃ {air?.ozone?.toFixed?.(0) ?? "—"}</strong><p>{pollen == null ? "Pollen data unavailable" : `Peak pollen: ${pollen.toFixed(0)}`}</p></article><article className={`rain-risk ${rainRisk.toLowerCase().replace(" ", "-")}`}><p className="eyebrow">HEAVY-RAIN RISK</p><strong>{rainRisk}</strong><p>{nextDayRain.toFixed(0)} mm forecast in the next 24 hours.</p><small>{nextDayRain >= 30 ? "Avoid flooded routes and watch official alerts." : "A forecast guide — official flood alerts appear above when issued."}</small></article><article><p className="eyebrow">RAIN PLANNING THRESHOLD</p><label>Plan for rain at {threshold}%<input type="range" min="20" max="90" step="10" value={threshold} onChange={e => { const value = Number(e.target.value); setThreshold(value); localStorage.setItem("weatherly-rain-threshold", String(value)); }} /></label></article></section>;
}
